### ISSUE TITLE
Use reflect damage item whenever possible

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/steamSummerMinigame#100]

**Comment by Xinayder** [comment]
Should it be used instantly or on boss levels?

**Comment by HxxxxxS** [comment]
It's useless on trash mobs if there are medics up. Right?

**Comment by Xinayder** [comment]
@hansskogvold I don't think so, because it reflects any damage you receive..

**Comment by HxxxxxS** [comment]
Idk, all i know is I have _never_ died in the room I'm currently in :smile:

**Comment by GreatOldOne** [comment]
Does reflect damage stacks?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Hmm, this Item is pretty useless on lower Levels because they do not enough Damage.
If it stacks, then it would be the best to use it when others activated it, especially on higher Levels.
I anyway never really seen an noticeable Effect from it, either the Damage dealt is too low or because it was never stacked, if it stacks, if it doesn't its pretty useless.

**Comment by xPaw** [comment]
I've simply used this item whenever available on levels above 5000. This can be tweaked if needed.
