### ISSUE TITLE
Elements not evenly distributed

### ISSUE THREAD

**Issue by DannyDaemonic** [SteamDatabase/steamSummerMinigame#180]
The best precision you can get with a Number is 53 bits [as per spec](http://ecma262-5.com/ELS5_HTML.htm#Section_8.5), but steamId is more than 53 bits, so parseInt drops bits. Try it with your own steamID, you'll probably get a different number.

Since 100 is evenly divisible by 4, we can use "g_steamID.slice(-2)%4".

Further discussion [here](https://github.com/ensingm2/SteamMonsterGameScript/issues/94). Near the end you can see some testing they did that backs up this assertion.

**Comment by ensingm2** [comment]
Tacking on to correct this issue:

You guys implemented your hashCode function to get around this, but the function itself doesn't result in an evenly distributed range. This leads to two sources of variance, once from the error in the hash implementation, and the other in the real world case that steamIDs used will be random-ish. This leads to more change from normal distribution than is necessary (extra sources of variance are bad).

Also, an unrelated note/suggestion:  Before assigning an element based on steamID you may want to see if there's already a specialized element, so you aren't wasting levels the user has manually upgraded before using the script.

EDIT: The 'g_steamID.slice(-3)%4' solution won't work either, as the range [0-999] is not divisible by 4, resulting in a non-uniform distribution (JK, I'm wrong)

**Comment by DannyDaemonic** [comment]
@ensingm2 I'm not familiar with the code, but there does seem to be a bit of code in there to check for that:

``` javascript
    if (leveled >= 2) {
        return;
    } else if (leveled == 1) {
        lockToElement(lastLeveled);
    } else {
        lockToElement(elem);
    }
```

**Comment by DannyDaemonic** [comment]
Just to clarify for this issue thread, the "99/999 is not divisible by 4" has come up in other places. Both 0-99 and 0-999 are evenly divisible by 4. We are dealing with base 0, and 0 through 99 is 100 different numbers.

**Comment by ensingm2** [comment]
> @ensingm2 I'm not familiar with the code, but there does seem to be a bit of code in there to check for that:

This actually doesn't work either. It has a lot of weird edge cases where things do or don't get locked.

For example:

my upgrades are: [fire: 2, water: 2, earth: 2, wind: 0]
nothing is levelled past 3, so it chooses based on my steamID
my steamID hashes and assigns me to wind. Oops! 6 levels lost.

or

my upgrades are: [fire: 3, water: 3, earth: 0, wind: 0] or something similar (2+ elements above level 3)
'More than 2 elementals leveled to 3 or above. Not locking' (by the way, you say 'more than' but compare >= here)
You  will now  never automatically upgrade an element

**Comment by DannyDaemonic** [comment]
@ensingm2 Sorry. You're misreading the code again. It simply locks nothing in the case you gave.

**Comment by wchill** [comment]
@ensingm2: I read the discussion.

What you're missing is that the original implementation of the hashCode(steamID64)%4 did not account for people choosing to upgrade an element before their lock (eg. old versions of the script that did not lock suddenly being updated). That was an edge case that I had not considered, and for most people it worked fine as I did not want to have the element lock jump around thanks to using an RNG. With this method, people were guaranteed to be locked to that specific element for the entire game.

(Now you may be wondering, why didn't I just use Local Storage or something? Well, tbh I didn't consider it at the time.)

The detecting whether a lock should be placed on an already upgraded element was put in place afterwards because of the reason I mentioned above. And the distribution of hashCode() is close enough to even that its being slightly uneven will not affect a lobby significantly (especially since there are people not using scripts and there are people who will leave the game early).

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Why not add Roomid to it, so at least the prefered Elements will change each Day, better than being stuck with the same. Like hash (SteamID + RoomID) instead of only SteamID. Or better, hash (RoomID \* SteamID / 4).

I also noticed too that my Element is over used... Levels with my Element have 100x more Damage then all others, coincidence or are all locked to the same?

**Comment by rossengeorgiev** [comment]
The current code produces the following distribution:

![a](https://cloud.githubusercontent.com/assets/2720787/8171882/6d4b1354-13b3-11e5-9ac2-12f176f16d52.png)

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@rossengeorgiev 

Really?

i'm on Earth now btw.

But still adding RoomID before hashing would be cool, cause being stuck at the same Element each Day is boring. ;)

**Comment by ensingm2** [comment]
> @ensingm2 Sorry. You're misreading the code again. It simply locks nothing in the case you gave.

You sure?

```
var hardCodedHashResult = 3;
var elementalLevels = [2, 2, 2, 0]; //fire, water, air, earth

function lockElements() {
    /*
        var elementMultipliers = [
        s().m_rgPlayerTechTree.damage_multiplier_fire,
        s().m_rgPlayerTechTree.damage_multiplier_water,
        s().m_rgPlayerTechTree.damage_multiplier_air,
        s().m_rgPlayerTechTree.damage_multiplier_earth
        ];

        var hashCode=function(str) {
            var t=0, i, char;
            if (0 === str.length) {
                return t;
            }

            for (i=0; i<str.length; i++) {
                char=str.charCodeAt(i);
                t=(t<<5)-t+char;
                t&=t;
            }

            return t;
        };
    */

    //Replace with our hardcoded test levels
    var elementMultipliers = [
        1 + (elementalLevels[0]*1.5),
        1 + (elementalLevels[1]*1.5),
        1 + (elementalLevels[2]*1.5),
        1 + (elementalLevels[3]*1.5)
    ];

    //Pretend we happen to land on our hardcoded element
    //var elem = Math.abs(hashCode(w.g_steamID) % 4);
    var elem = hardCodedHashResult;


    // If more than two elements are leveled to 3 or higher, do not enable lock
    var leveled = 0;
    var lastLeveled = -1;

    for (var i=0; i < elementMultipliers.length; i++){
        console.log("Element " + i + " is at level " + (elementMultipliers[i]-1)/1.5, 3);
        if ((elementMultipliers[i]-1)/1.5 >= 3) {
            leveled++;
            // Only used if there is only one so overwriting it doesn't matter
            lastLeveled = i;
        }
    }

    if (leveled >= 2) {
        console.log("More than 2 elementals leveled to 3 or above, not locking.", 1);
        //return;
    } else if (leveled == 1) {
        console.log("Found existing lock on " + lastLeveled + ", locking to it.", 1);
        //lockToElement(lastLeveled);
    } else {
        console.log("Locking to element " + elem + " as chosen by SteamID", 1);
        //lockToElement(elem);
    }
}

lockElements();
```

Seems to show my point.

**Comment by DannyDaemonic** [comment]
If we choose data that starts out evenly distributed, hashing won't even be necessary. The last 2 digits of the steamID should be sufficient:

``` javascript
parseInt(g_steamID.slice(-2)) % 4
```

One could even combine it with room number as suggested:

``` javascript
( parseInt(g_steamID.slice(-2)) + parseInt(g_Minigame.gameid)) % 100 ) % 4
```

**Comment by DannyDaemonic** [comment]
> You sure?

@ensingm2 Yes. Look at the if statements at the end of the code you pasted. What happens if the user has leveled more than 2 elements?

``` javascript
    if (leveled >= 2) {
        return;
    } else if (leveled == 1) {
        lockToElement(lastLeveled);
    } else {
        lockToElement(elem);
    }
```

If the user has leveled more than 2 elements, as per your example (`elementalLevels = [2, 2, 2, 0]`), the script _returns_. It does _not_ call lockToElement. If they had leveled 1 element, it locks to that element. It only uses the element chosen by steamID in **one** case, and that's when the user has leveled no other elements.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I suggest ( ((parseInt(g_steamID.slice(-4)) \* parseInt(g_Minigame.gameid.slice(-3)) / 3) % 100 ) % 4

Added ( / 3) to distribute better else 0 and 2 are overrepresented.

So its 4 Digits \* 3 Digits(the 3 last Digits of RoomID are the most significant) and with added RoomID in Calculation there is some Variation each Day which one is selected, less boring...

**Comment by rossengeorgiev** [comment]
> If we choose data that starts out evenly distributed, hashing won't even be necessary. The last 2 digits of the steamID should be sufficient

Yep. Here is with just mod 4

![a](https://cloud.githubusercontent.com/assets/2720787/8172248/8c7307de-13b6-11e5-8270-1eff65837834.png)

**Comment by ensingm2** [comment]
@DannyDaemonic

> Yes. Look at the if statements at the end of the code you pasted. What happens if the user has leveled more than 2 elements?

`// If more than two elements are leveled to 3 or higher, do not enable lock`
leveled therefore stays 0 (incrementing it is dependent on the element level being >= 3), results in a lock on the hash result (hardcoded to 3 in this case to demonstrate a point)

Run the test code in an empty tab if you don't believe me. It runs independently of the game/other scripts.

**Comment by DannyDaemonic** [comment]
@K4r0qtuYNE5G4qgZ Multiplying like can have a shifting effect, which is especially dangerous when modding by a small number. Adding is probably best. Also, for a range of [0-999] you only need slice(-3). To use 4 digits try:
`( parseInt(g_steamID.slice(-3)) + parseInt(g_Minigame.gameid)) % 1000 ) % 4`

@rossengeorgiev What would be a better comparison to current room vs steamid%4 would be a comparison using javascript's ParseInt (which rounds off bits) and the hash methods in the script generate distributions.

@ensingm2 I stand corrected. I was only looking at the if statement logic itself, not the run up to how it decided what was leveled. Yes, that should probably be changed. I kind of feel that particular issue has derailed the distribution issue that was the original topic here.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@DannyDaemonic

Yeah, just noticed the Problem, tried to optimize with division per 3 but somehow it's not solving it, always 2 and 0 overrepresented...

So adding is actually better indeed.

So  ... ( parseInt(g_steamID.slice(-3)) + parseInt(g_Minigame.gameid.slice(-3)) % 100 ) % 4  ... then?

**Comment by DannyDaemonic** [comment]
The current hash method used adds 10 or more lines of code. In the end, I think simpler code is better, and this is just one line of code:

``` javascript
parseInt(g_steamID.slice(-2)) % 4
```

Even combine with room number as suggested by K4r0qtuYNE5G4qgZ, it's still fairly simple:

``` javascript
( parseInt(g_steamID.slice(-2)) + parseInt(g_Minigame.gameid)) % 100 ) % 4
```

As for choosing the wrong element. A quick band-aid would be just changing `if ((elementMultipliers[i]-1)/1.5 >= 3)` to `if ((elementMultipliers[i]-1)/1.5 >= 1)`.

**Comment by LeoVerto** [comment]
Hey, people arguing about code I wrote!

`// If more than two elements are leveled to 3 or higher, do not enable lock`
You're right, this should say "if two or more elements" instead.

This code was written before we had any option or property storage system in place, hence wchill's decision to use the SteamID to chose the element lock. The first if probably isn't even necessary anymore as there's now a big checkbox to disable element locking.

@DannyDaemonic `leveled` is only increased if an element is at level 3 or above: 

> if ((elementMultipliers[i]-1)/1.5 >= 3) {
> leveled++;

This decision was made by @chauffer on IRC.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@DannyDaemonic

i prefer

`( parseInt(g_steamID.slice(-3)) + parseInt(g_Minigame.gameid.slice(-3)) % 100 ) % 4`

So the 3 last Digits of SteamID and GameID are added together. Because the GameID is 5 Digits but only the last 3 are significant, the first is always 4 and the second is always 1 or 2.

Also yeah no need for a hashfunction that way.

**Comment by ensingm2** [comment]
Why add them together at all?

For the function to work at all, both components need to be normally distributed and in a range that's a multiple of 4 (whether you slice(-2) or slice(-3), whatever) anyway, and you just get another normalized distribution by summing them. You don't actually gain anything, unless I'm mistaken.

either way, you end up with a normally distributed [0-3] range, and reducing it to a single variable is cleaner and needs fewer computations.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@ensingm2

Because i want have a Variation of selected Elements each Day and not being stuck to the same because SteamID is static, that's all, it hasn't anything to do with optimizing Distribution.

Also i find it cleaner to simple take the last 3 Digits of both and adding them, nice and clean. ;)

**Comment by ensingm2** [comment]
So...  in that case why don't you just `Math.floor(Math.random() * 4)` for the element?

You're essentially using steamID + gameID as a PRNG based on the (**_most likely**_ true) assumption that the distribution of both variables is approximately normal.

[Javascript's random generator is defined to be approximately normal](http://www.ecma-international.org/ecma-262/5.1/#sec-15.8.2.14) (as long as you aren't using a random shoddy browser with incorrectly implemented functions), so it takes the previous assumption out of the equation for the same result.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@ensingm2 

Because it should be Daybased only, GameID only change each Day unlike Math.floor(Math.random() \* 4) that would produce Random Numbers on each run.

So ...
`( parseInt(g_steamID.slice(-3)) + parseInt(g_Minigame.gameid.slice(-3)) % 100 ) % 4`

... is just perfect for that purpose, no need for any hashes or randomfunctions.

SteamID is static anyway per User and GameID's last 3 Digits are Random enough but only changes per Room you join.

Or also only execute Math.floor(Math.random() \* 4) once per Game join, doesn't matter for me, i simply not want to be stuck at one Element for ever. LOL!

**Comment by ensingm2** [comment]
the random would produce new numbers each run, but is overridden if  larger leveled element is detected.

Case: starting game: elementLevels: [0,0,0,0]
    `Math.floor(Math.random() * 4)`:  chooses random element
    `( parseInt(g_steamID.slice(-3)) + parseInt(g_Minigame.gameid.slice(-3)) % 100 ) % 4`: chooses 'random' element

Case: resuming game: elementLevels: some element is > level 3
    `Math.floor(Math.random() * 4)`:  chooses random element, is then overridden by leveled detector
    `( parseInt(g_steamID.slice(-3)) + parseInt(g_Minigame.gameid.slice(-3)) % 100 ) % 4`: chooses same element, is then overridden by leveled detector

The only case where behavior differs between the two is the error cases I mentioned earlier in this post (levels [2,0,0,0], [3,3,3,0], etc). That's due to errors in that section of code and not relevant to this. These cases will have issues despite which PRNG you choose.

EDIT: Additionally, by using rand you're using only rand, a multiplier, and math.floor. Your version slices two strings, has to parse both of them for an int, add them together, then mod twice.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@ensingm2

You should stick to one, upgrading multiple is waste of Money and inefficient.

The Idea is that Elements are optimized across Team, if whole Team has well distributed Elements that are fully upgraded its the best. Even upgrading one other means waste of Money because they become expensiver all together, so instead haven 3 other on 1 you could have one on 17 instead 14 at that Time.

Of course only works if whole Team uses Script and Elements are distributed well across Team and per Room.

Also how to check what other have? Don't think that's possible.

**Comment by tleunen** [comment]
If you really want something well distributed, you could deploy a little service that the game will call to get which element the user has to focus on.
Everytime a new user calls it for a specific game id, you switch to the next element.

**Comment by ensingm2** [comment]
@K4r0qtuYNE5G4qgZ 

> You should stick to one, upgrading multiple is waste of Money and inefficient.
> 
> The Idea is that Elements are optimized across Team, if whole Team has well distributed Elements that are fully upgraded its the best. Even upgrading one other means waste of Money because they become expensiver all together, so instead haven 3 other on 1 you could have one on 17 instead 14 at that Time.
> 
> Of course only works if whole Team uses Script and Elements are distributed well across Team and per Room.

...What? I'm not arguing that. This doesn't relate to what I said at all. The only time I even mentioned leveling multiple elements is as an error case that you need to handle regardless for people that start using your script after they already started a game and manually bought upgrades.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@ensingm2

Isn't the lock Elements Upgrades Box for that?

If Elements would upgrade automatically then it would matter, but else just disable the lock.

Also what i mean is only the first selection if i have enabled that Box, so that the preselected one changes each Day, that's all.

Also probably after a while this Discussion has started to mix up different Things. Everything i wrote had only to do with being stuck on one Element selection because SteamID is static. And others started to analyze the Distribution itself and ... well many different Things. LOL!

**Comment by ensingm2** [comment]
OK, let me try to explain this differently.

The point of this code is to choose a single element to focus on (lock to).

When you run lockElements(), the program attempts to pick an element to use, with the following conditions:
- If the program detects that a single element is already being focused, it overrides everything else and locks you to that element (This section of code is actually kind of messed up, see the bug cases that I posted earlier, but that's another issue) This is implemented in [Lines 806-817](https://github.com/SteamDatabase/steamSummerMinigame/blob/master/autoPlay.user.js#L806-828)
- If the program does *_NOT_ detect an element already being focused on by the user, it will pick one using some function (this is the function we're debating)

So, the only time this function (some PRNG) runs is when we need a newly chosen specialization, and it doesn't matter **which** element is chosen, so long as over the base of all users, it is approximately normally distributed. This is [Line 804](https://github.com/SteamDatabase/steamSummerMinigame/blob/master/autoPlay.user.js#L804)

Now, since it doesn't matter which we choose at this point, we want to use the most computationally efficient, and simple code that still gurantees as close to normal distribution over all users as possible.

`Math.floor(Math.random() * 4)` is much more efficient to run, is shorter, simpler code, and is defined by coding standards to have approximately normal distribution.

`( parseInt(g_steamID.slice(-3)) + parseInt(g_Minigame.gameid.slice(-3)) % 100 ) % 4` is more computationally heavy, more confusing to anyone reading the code, and relies on the _assumption_ that both steamID and gameID are normally distributed, which they most likely are. That said, it's always best not to rely on assumptions wherever possible.

So, both functions are essentially a PRNG for a range of ints from  [0-3] to be used when no element is already focused on (basically, when they player is just starting a new game). They have the same function.

Your argument that the random code would change your focus mid game or on a refresh is not valid, because of the first condition of picking a lock element. If you are mid game, the above code (should) detect that there is already an element being focused on, and that override triggers, making both PRNG functions proposed irrelevant.

Am I being clear?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@ensingm2 

Yeah, so like i said already, simply use Math.floor(Math.random() \* 4) once per Game join and everything is fine and two Fly's slapped at once because then (most probably) i'm not stuck to the same Element each Day also.

**Comment by xPaw** [comment]
> is more computationally heavy

Seriously? If using parseInt is your biggest concern about performance, you should see what Valve is doing in this minigame. There's a reason I added game renderer throttling.

At most, this should be random and simple enough to read:
`( g_steamID.slice( -3 ) + g_GameID ) % 4`
