### ISSUE TITLE
Disable Auto Use Ability - Like-New & Throw Money (10% Gold to Damage)

### ISSUE THREAD

**Issue by deuxdoom** [SteamDatabase/steamSummerMinigame#243]
THROW_MONEY_AT_SCREEN
TREASURE
LIKE_NEW
WORMHOLE
FEELING_LUCKY

auto use is not good...  just all !

**Comment by Sanaki** [comment]
Wormholes appear to be being handled better in #190, #233, and #245. I know I saw mention of Treasure in #237. Feeling lucky seems to be useless and spammable any time for the same effect, so that one's irrelevant in my opinion. Like new I'm not sure has been addressed. Throw money at screen should be being handled as a last-hour implementation in one of the issues as well, though I'm blanking on where I saw it.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Also why not quickly buy all possible Upgrades just before THROW_MONEY_AT_SCREEN this Money spend before, 10% Damage for almost no Money used...

Btw. THROW_MONEY_AT_SCREEN is sometimes the only Solution to kick the Boss because no one has Nukes and Stuff left... LOL

**Comment by rossengeorgiev** [comment]
There is a toggle to do that now.
