### ISSUE TITLE
Autoupgrade stops upgrading health after 300k

### ISSUE THREAD

**Issue by wn-mitch** [SteamDatabase/steamSummerMinigame#251]
People are starting to get one shot now that we passed 100k levels

**Comment by rossengeorgiev** [comment]
You are dying with 300k hp?

**Comment by wn-mitch** [comment]
I'm not but others were

**Comment by K4r0qtuYNE5G4qgZ** [comment]
yeah i have over 9115K HP and its decreasing slowly... ;)

Best is to upgrade to (10, 10 , 10, 10,..) perhaps based on Deaths Count LOL or Levelbased?

But i still upgrade manually, better Control, i don't thrust Autoupgrades

Also till Level 2000 about 1'014K HP is save but then start to need more

**Comment by Sanaki** [comment]
I was about to report this myself. It should suffice to make it increase the cap it upgrades to based on what level you've achieved. Probably just as high as 800k or so at level 10k, and on into the next tier at 100k. My team's only in the 12k level range, so I'll have to yield to someone higher up toward how much is necessary.

EDIT: Actually, the simple route could be better in this case. If your hp ever manages to drop below a set percentage (25-33%?) while at cap, increase the cap. Autorefresh would likely interrupt this, but if the cap genuinely needs to be increased, your health will hit a low again before too long anyway.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
A rather save Calculation to never die...

~2000 - 1'000K HP
~5000 - 2'000K HP
~9000 - 3'000K HP
~14000 - 4'000K HP
~20000 - 5'000K HP
~27000 - 6'000K HP
~35000 - 7'000K HP
~44000 - 8'000K HP
~54000 - 10'000K HP
~continue ;)

Also looks like they breaking Level 300'000 Mark today

**Comment by Sanaki** [comment]
Is there a reason not to just use an autoincrease based on whether your health is actually dropping? From what I can tell, it'd be more futureproof in case they decide to adjust mob damage to make the 5th-7th tiers useful. An actual dps received measure compared against your max health would be better, but I'm not sure how feasible that is.

**Comment by GreatOldOne** [comment]
I've been running like this for all these days:

Until level 1000:

{10. 5, 0, 0, 0 ,0}

After level 1000:

{10, 10, 5, 0, 0 ,0}

I never die and those points are almost costless later on.

**Comment by milkfat** [comment]
I died with 333K HP at level 120 000. I didn't notice any deaths previously (doesn't mean there weren't any). My HP is constantly fluctuating now.

Just died 4 times on the 123 000 boss, although I'm resurrected immediately by all the Resurrections being spammed. It may be time to boost health beyond 300K HP.

**Comment by tleunen** [comment]
that's weird. I never dies with 300k. I guess the value depends on the room as well since it depends on the potion.
Maybe detect if (hp < 25%) then increase the HP when > lvl 100k?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I have 10'000K HP and it goes down to 6'000K then Medic fills up, so if i had 4'000K i would be dead, happens not a lot but happened, so better have a safe margin... ;)

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I now die each 10 seconds with 1'000M HP so you will need to upgrade way beyond fast...

Also Auto Upgrade doe snot work, i die each 10 seconds and it does nothing...

So at least upgrade immediatelly the least expensiv on if Health goes beyond 25% so that you heal, or something like that... I will now Update beyond 10'000M manualy...

Ok Room is dead and Auto Upgrade Health doesnt work, seems all People are away and dying every Seconds, Game Over ...

BTW. you must upgrade beyond Tier 6 and the last one cost 120B to get to Tier 7 ... Also the Auto Upgrade Heaöth not even highlight anything, does simply nothing while i die and die and die... LOL!

Based on what i watched its more like

~2000 - 1'000K HP
~10000 - 10'000M HP
~30000 - 10'000B HP
~60000 - 10'000T HP
~continue ;)

Hmm, but strangely it was only for some Minutes, now with 10'000M i seem not to get any Damage at all, interessting, maybe some Levels are deadly and then again normal or was it a Server Bug?

Server tried to kill us.. LOL

Yeah it was Glitch but now they deal 1M Damage per Second, so you need more as 1'000K for sure, and i suppose most have enabled Auto Upgrade Health and are away, now the Room is half Dead and nobody there to upgrade... So not good, we loose thousands of Levels already... LOL!

Ok a quick Calculation showed Problem, (30 \* Level) is not enough, must be at least (300 \* Level) to be safe...

Yeah, well i suppose its over ... Team Health Flatline ... now... :(

**Comment by Sanaki** [comment]
Just checked in, on wave 23,800 we're taking about 200k dps on spawner sets and 350k dps from the boss. The current "fix" only provides for about 700k health at this level. It does need to be increased, whether as needed or by set intervals.

**Comment by rossengeorgiev** [comment]
This issue should be resolved by above PR.
