### ISSUE TITLE
Encoded Room Number Joining Feature

### ISSUE THREAD

**Issue by sordidfellow** [SteamDatabase/steamSummerMinigame#253]
Question:
  Can a "Join" box be added to the minigame page that accepts an encoded room #? Entering an encoded string and then having it's own join button that would run JoinGame behind the scenes with the actual room number.
 If the encoding is changed every so often, then only folks with latest script version could get into the room.  By running the JoinGame behind the scenes, only folks who get into the room would know the number, which would limit folks announcing it for non-scripters...

**Comment by MatthewClair** [comment]
What would stop someone from getting the decoded number from the script and then distributing that number anyways?

**Comment by sordidfellow** [comment]
If they modified the script to reveal that number?  or if they announced it once they got in to the room?  Nothing could stop that.  But it could create a bigger window for folks with the latest scripts and motivate some people to update...  Especially if the version of the script/room enc was right next to the box.

It's definitely a lot of work to give a small advantage to the latest script users.  More of a "nothing else to update in the script, why not do this" kind of a feature.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Also something else, did you notice that you can exit and join other Rooms now? 10 Minute Limit is gone! I exited and joined another with 30000 more Level without Problem... ;)

Also it was bugged, i exited and spammed in Console, i joined new room, got Error but had all Abilities and everything i got before still listed....

Instantly got Billions of Money out of nowhere and was able to buyed everything at once.

So Limit was lifted but there was something strange going one in my Case... ;)

**Comment by Autositz** [comment]
Rumors are, that once you leave a room, you are unable to join back into that room to prevent hopping.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, but i joined another that was 6 Hours in Game already and 30000 Level higher then other i exited... 

Also there something else that is odd, my highest Level raised from alone on each Refresh, but the current was lower than highest, looks like something is broken... I wonder, i wonder if Clickrate is broken too

BTW. Level 335943 has been reached, so max 300000 Mark already passed!! LOL

EDIT: Max Clickrate is still 20 :(

But strange also that the ones that reached 335943 are Unknowns and a new Room, so who knows what happened... ;)

LOL!! We have a Level Time of -1:0:-1 for 10 Levels, that means i see -1:0:-1 briefly and then Boss comes with Limit Frames activated LOL!!!

**Comment by Sanaki** [comment]
Earlier people room hopping somehow managed to knock me out of my room and into another. My max level achieved continued to rise with the original though, and a few hours later I magically landed back in it on a refresh with no idea how or why. Not sure if it's this sort of manual join causing it, but if so, I wouldn't want to see it embraced by the script's frontend.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
The Script is going havoc currently ... Time of -1:0:-1 for 10 Levels ... Abilities desynced ... completely, also the Cooldown spam before Ability causes to reset the Cooldown completly 50% of timess, dunno why, but there are at least 109 People using the same Script now, almost every Ability has Cooldown now and sometimes even goes instantly back to 0 and its respamed, crazy, with Limit Frames its like, Boss, Boss, Boss, Boss, Boss... Also i think the Script is now to slow to handle, it disables, enable, disables Abilities and well desynced totally, also Abilities and Stuff going across Levels, things going so fast now that if you trigger it at Level 1 it lands on Level 14 sometimes...

Also i don't what happened with the Rooms and Stats, looks like Limit is gone and Server is desynced too somehow, because its like i'm in two Rooms at the same Time, but its funny somehow... Probably now almost all People are using some Scripts... I can also Identify some from what they do, the each 250 Level Gold Rain also works very well, sometimes over 1000M Gold per Sec, thats nice...

I also disabled targeting pointer because its pointless anyway and probably eats some Frames for nothing, i don't see the normal Levels anyway...

Btw. they reached Level 543499 now...

**Comment by xPaw** [comment]
Out of scope.
