### ISSUE TITLE
WH strategy tweak suggestion

### ISSUE THREAD

**Issue by Thiana** [SteamDatabase/steamSummerMinigame#271]
The problem with the current WH strategy is once the room is out of WHs the DPS for that room basically dies for long periods on expected WH levels. 

Is it possible to track when a WH was last used, and if one wasnt used in the last 15 minutes(?) use the normal full dps for a boss?

**Comment by tleunen** [comment]
We could detect it...

``` javascript
var isWormholeUsed = $J('#activeability_26').is(':visible');
```

**Comment by joosera** [comment]
![Ship it.](http://forthebadge.com/images/badges/fuck-it-ship-it.svg)

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Is that Issue releated to #277 #284 somehow? Because all 50 Levels or Abilities are locked and Boss stays there and nothing happens and i can't nuke it because everything is disabled.

Costs us 100000 of Levels already!

**Comment by xPaw** [comment]
@K4r0qtuYNE5G4qgZ not nuking the boss is part of the strategy.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Well, but if it disables all Abilities and Boss stays there for 2 Minutes its a bad Strategy not?

Somehow its not tracked right, it disables, enables, disables, enables in 10 Seconds intervall and then stays locked every 20-50 Levels and exactly when a Boss is there nothing happens and stays there for 30 Sec - 2 Minutes

**Comment by xPaw** [comment]
The point is to use as many wormholes as possible. People have over 1,000 of them at this point, and it takes time to use them all.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
So this is Lag or what?

But Expected Level gone down 500000 because of that already, so will this recap later or what?

Also WH was spammed the first 30000 Levels, perhaps over 1000 easly... Is that the Reason? Lag?

Also why it's stuck to Bosses so long without anyone nuking it? I don't understand what should be the Strategy of it, even with WH you need to kick Bosses fast to progress.

**Comment by gaetan-petit** [comment]
I'm obviously in a room out of WH, I think @Thiana is right wee need something when this happen.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Same Situation, but after patching #292 in locally and given some others in Room the Flow goes on again even without much WH, one here and then and it flows... I also removed the Level 100 disabled Autoclick too, i put 997 instead of 100 its a Prime so not really frequent... ;)

Also with #292 some Cooldown Reset Items here and then works wonder, its like WH then but without WH... It bleeds over 20-40 Levels sometimes...

Perhaps a Option in Options to change the (100) Level or disable this thing temorarely would also be nice or i don't know something simmilar that works auto...

**Comment by bountygiver** [comment]
the current strategy is to switch to a slightly lower level room when you are out of WH, so you get your WHs refilled and carry the room to a higher level, and the next switch you will have even more WH and starting on a high level, so the original issue is not something that needs to be worried about

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Yeah, but i need to Level up first a bit to get enough WH's also currently others seem to have enough, 10-20 thrown in per Minute...

EDIT: Now the WH Strat in our Room is in perfect Sync, jumps perfectly to 500 almost every time and the next bunch of WH's comes in for the next jump to 000 is probably how its intended to work.
