### ISSUE TITLE
is non-optimal Raining Gold use beneficial after a point?

### ISSUE THREAD

**Issue by rcaputo** [SteamDatabase/steamSummerMinigame#294]
Would it be beneficial to burn some Raining Gold if:

(total cooldown of accumulated Raining Gold > remaining game time - 7200)
or
(count of Raining Gold on hand > (likely level - current level) / 10)

[Added -7200 because you want time to use the things that gold is spent on.]

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Well, i got 178 Raining Gold and it's never used so far, but there is also barely Time to throw in and the disable Autoclick on 500 Level is sub-optimal, loose 10-20 Billions per Second because 90 is overshot 99% of Time anyway and also it does not Autoclick on 100 Level too, dunno why and then you land on a 500 where People throwing 10-20 raining Gold and it also doesn't Autoclick.

I set the 500 to 501 now to enable Autoclick again and also set the 100 to 997 to allow Autoclicking on 100 Level again (its strange the 100 is called raininground but it doesn't Autoclick, so is this a Bug or?) it does only on 10 Level but not on 100 Level.

But still Raining Gold never thrown in by myself, either it's to fast currently or i dunno but others are throwing in 10-20 at 100 Level including 500 and strangely its almost everytime a 500 Levele where you have about 5 Seconds Time to Autoclick, the 10 Level including 90 are skipped 99% of Time and 100 about 50% and then you land on 500 so if you don't want going empty on Money Autoclick should never by disabled to at least get those 3-5 Seconds Gold Rain on every Occasion possible.

They are throwing in 100-500 Wormholes currently, it's not a top notch Room but at least the flow goes on, i almost runned out of Wormholes anyway now, only have about 120 left...

So for me throwing in Raining Gold at 500 Level would be good to max it there where all are throwing in, because if you only have 5 Seconds max, its good if it goes to 5'000M-10'000M but also only throw in if there is enough Time like it is coded anyway currently. I don't know why it never throws in it gone up to 234 available now, not a single used... LOL!
