### ISSUE TITLE
Keeps switching away from bosses

### ISSUE THREAD

**Issue by NolanSyKinsley** [SteamDatabase/steamSummerMinigame#299]
I updated to the latest, 5.0.5, and now every time it turns to a boss it turns away and back to the boss.

**Comment by zeflap** [comment]
Intended behavior AFAIK, to stop nukers benefitting from likenews fired to use more wormholes.

**Comment by NolanSyKinsley** [comment]
actually... now that I watch it, it is switching away from every intended move it does... it keeps moving to empty lanes

**Comment by zeflap** [comment]
Huh.

**Comment by irisfofs** [comment]
I've noticed this too for a while but haven't been able to figure out any pattern. The script seems more switch-happy than before.

**Comment by rossengeorgiev** [comment]
> Intended behavior AFAIK, to stop nukers benefitting from likenews fired to use more wormholes.

There is no such behavior currently.

**Comment by NolanSyKinsley** [comment]
it wasn't this way in 4.0.1

**Comment by NolanSyKinsley** [comment]
I think I see the pattern, it is whenever the script is attempting to use an offensive ability, it is not using my rain gold but any time it switches to a boss that it should be used on it switches away from the boss instead of using the ability.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
@NolanSyKinsley 
Ohh you are right, i did not notice it because the Limit frames per second is enabled of course, but what i see since a while is that on every boss the Boss vanishes shortly and then reappears, its more like a flicker with Limit frames per second enabled, but that's of course exactly what causes that short flicker, it switches away to a empty lane and back again.

But with enabled Limit frames per second its really hard to see, i supposed its the Game lag causing it.

Also this is probably the Reason why Raining  Gold is never used, because its an empty lane exactly at that moment.

Disabled LFPS and yeah its switching to Boss, Empty Lane, Boss about ~75% of all cases, also seen it does it too for normal Mob's too sometimes.

**Comment by NolanSyKinsley** [comment]
I have seen that this is not detrimental to correct play, it was interfering with my play style which I found out was the absolute wrong way to play. Whether this bug is intended or not, it is not detrimental to optimal play conditions.
